name = "Javis"
uuid = "78b212ba-a7f9-42d4-b726-60726080707e"
authors = ["Ole Kr√∂ger <o.kroeger@opensourc.es>", "Jacob Zelko <jacobszelko@gmail.com>"]
version = "0.1.2"

[deps]
Animations = "27a7e980-b3e6-11e9-2bcd-0b925532e340"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
FFMPEG = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"
GtkReactive = "27996c0f-39cd-5cc1-a27a-05f136f946b6"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
VideoIO = "d6d074c3-1acf-5d4c-9a43-ef38773959a2"

[compat]
Animations = "0.4"
Cairo = "1.0.4, 1.0.5"
ColorTypes = "0.10.9"
FFMPEG = "0.3, 0.4"
Gtk = "1.1.4"
GtkReactive = "1.0.3, 1.0.4"
Images = "0.20, 0.21, 0.22"
LaTeXStrings = "1.1"
LightXML = "0.9"
Luxor = "~2.0, ~2.1, ~2.2, ~2.3, ~2.4"
ProgressMeter = "1"
VideoIO = "0.6, 0.7, 0.8"
julia = "1.4"
