name = "Javis"
uuid = "78b212ba-a7f9-42d4-b726-60726080707e"
authors = ["Ole Kr√∂ger <o.kroeger@opensourc.es> and Jacob Zelko <jacobszelko@gmail.com>"]
version = "0.1.1"

[deps]
FFMPEG = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
FFMPEG = "0.3, 0.4"
LaTeXStrings = "1.1"
LightXML = "0.9"
Luxor = "2"
julia = "1.4"

[extras]
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
ReferenceTests = "324d217c-45ce-50fc-942e-d289b448e8cf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
VideoIO = "d6d074c3-1acf-5d4c-9a43-ef38773959a2"

[targets]
test = ["Images", "ImageIO", "ImageMagick", "ReferenceTests", "Test", "VideoIO"]
